version: '3.6'

networks:
  fastfeet-network:
    driver: bridge

services:
  fastfeet-api:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - POSTGRESQL_HOST=fastfeet-postgresql
      - REDIS_HOST=fastfeet-redis
    depends_on:
      - fastfeet-postgresql
      - fastfeet-redis
    networks:
      - fastfeet-network
    links:
      - fastfeet-postgresql
      - fastfeet-redis
    container_name: fastfeet-api
    command: yarn dev
    ports:
      - 3333:3333

  fastfeet-queue:
    build: .
    volumes:
      - .:/home/node/api
    environment:
      - POSTGRESQL_HOST=fastfeet-postgresql
      - REDIS_HOST=fastfeet-redis
    depends_on:
      - fastfeet-postgresql
      - fastfeet-redis
    networks:
      - fastfeet-network
    links:
      - fastfeet-postgresql
      - fastfeet-redis
    container_name: fastfeet-queue
    command: yarn queue

  fastfeet-postgresql:
    image: bitnami/postgresql:latest
    container_name: fastfeet-postgresql
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - POSTGRESQL_USERNAME=${POSTGRESQL_USER}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASS}
      - POSTGRESQL_DATABASE=${POSTGRESQL_NAME}
    ports:
      - '5432:5432'
    volumes:
      - /tmp/postgresql:/bitnami
    networks:
      - fastfeet-network

  fastfeet-redis:
    image: bitnami/redis:latest
    container_name: fastfeet-redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASS}
    ports:
      - '6379:6379'
    volumes:
      - /tmp/redis:/bitnami/redis/data
    networks:
      - fastfeet-network
